name: Publish to NuGet

on:
  push:
    branches:
    - master
    paths:
    - 'NStack/NStack/**'

jobs:
  publish:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.403

    - name: Clean
      run: dotnet clean NStack/NStack.sln --configuration Release && dotnet nuget locals all --clear

    - name: Install dependencies
      run: dotnet restore NStack/NStack.sln

    - name: Build
      run: dotnet build --configuration Release --no-restore NStack/NStack.sln

    - name: Generate NuGet package
      run: |  
        cd NStack/NStack
        dotnet pack --configuration Release --output out --no-build

    - name: Push generated package to NuGet.org
      run: dotnet nuget push **.nupkg --skip-duplicate --no-symbols true --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_API_KEY }}
